### PR TITLE
Add integration tests

### PR DESCRIPTION
**Pull request by digitalsadhu**
Adding a first pass of integration tests for the various endpoints

### CODE REVIEW

**Comment by trygve-lie** [comment]
We should write a testing sink which writes just to memory and which contains extra methods one can use to assert against and trigger misc behaviour on.

That saves us from having to clean up files etc in the tests plus it would be easy to populate such a sink with data without doing uploads to test etc.

It would also make it possible for us to create misc error scenarios which is hard to test with the file system. Ex, I would like to be able to test what happens if the file system fails in the middle of an upload etc.

**Comment by digitalsadhu** [comment]
yup, sounds like a good idea

**Comment by digitalsadhu** [comment]
Good to have some integration tests on the different sinks as well

**Comment by trygve-lie** [comment]
> Good to have some integration tests on the different sinks as well

Yeah. I do though see them as living in separate repos though.

**Comment by digitalsadhu** [comment]
yea thats a good idea

**Pull request merged**
